ln -s /home/douglasdrumz/Developer/dotfiles/aliases ~/.aliases
ln -s /home/douglasdrumz/Developer/dotfiles/bashrc ~/.bashrc
ln -s /home/douglasdrumz/Developer/dotfiles/gitconfig ~/.gitconfig
ln -s /home/douglasdrumz/Developer/dotfiles/gitignore ~/.gitignore
ln -s /home/douglasdrumz/Developer/dotfiles/inputrc ~/.inputrc
ln -s /home/douglasdrumz/Developer/dotfiles/path ~/.path
ln -s /home/douglasdrumz/Developer/dotfiles/spacemacs ~/.spacemacs
ln -s /home/douglasdrumz/Developer/dotfiles/tmux.conf ~/.tmux
ln -s /home/douglasdrumz/Developer/dotfiles/variables ~/.variables
ln -s /home/douglasdrumz/Developer/dotfiles/xmobarrc ~/.xmobarrc
ln -s /home/douglasdrumz/Developer/dotfiles/Xmodmap ~/.Xmodmap
ln -s /home/douglasdrumz/Developer/dotfiles/xmonad ~/.xmonad
ln -s /home/douglasdrumz/Developer/dotfiles/zcompdump ~/.zcompdump
ln -s /home/douglasdrumz/Developer/dotfiles/zshrc ~/.zshrc
