ln -s `pwd`/aliases ~/.aliases
ln -s `pwd`/bashrc ~/.bashrc
ln -s `pwd`/gitconfig ~/.gitconfig
ln -s `pwd`/gitignore ~/.gitignore
ln -s `pwd`/inputrc ~/.inputrc
ln -s `pwd`/path ~/.path
ln -s `pwd`/spacemacs ~/.spacemacs
ln -s `pwd`/tmux.conf ~/.tmux.conf
ln -s `pwd`/variables ~/.variables
ln -s `pwd`/xmobarrc ~/.xmobarrc
ln -s `pwd`/Xmodmap ~/.Xmodmap
#ln -s `pwd`/xmonad ~/.xmonad
ln -s `pwd`/zcompdump ~/.zcompdump
ln -s `pwd`/zshrc ~/.zshrc
