
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-01T12:00:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "552b8e27d47b1907cf8d8a920cedd326a3083237",
 "version": "4.1.1a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
